trigger:
  - "*"

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: sudo apt install shellcheck
    displayName: "Install shellcheck"
  - script: shellcheck hpriser
    displayName: "Check script"
